In [1]:
import matplotlib.pylab as pl
import numpy as np
import xgboost
from sklearn.model_selection import train_test_split

import shap

/home/rizkiduwinanto/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
X, y = shap.datasets.nhanesi()

In [3]:
X

,sex_isFemale,age,physical_activity,serum_albumin,alkaline_phosphatase,alkaline_phosphatase_isUnacceptable,alkaline_phosphatase_isTestnotdone,SGOT,SGOT_isUnacceptable,SGOT_isTestnotdone,...,urine_hematest_isLarge,urine_hematest_isBlankbutapplicable,sedimentation_rate,sedimentation_rate_isBlankbutapplicable,uric_acid,uric_acid_isUnacceptable,uric_acid_isTestnotdone,systolic_blood_pressure,pulse_pressure,bmi
20751,False,51,3,NaN,85.0,False,False,NaN,True,False,...,False,False,NaN,False,6.2,False,False,110.0,40.0,25.406803
20753,False,41,2,NaN,68.0,False,False,2.27,False,False,...,False,False,NaN,False,7.7,False,False,136.0,54.0,24.588331
20754,True,31,2,NaN,61.0,False,False,1.86,False,False,...,False,False,NaN,False,4.9,False,False,110.0,24.0,23.756502
20755,False,48,2,NaN,58.0,False,False,NaN,True,False,...,False,False,NaN,False,8.4,False,False,126.0,36.0,28.610011
20756,True,29,3,NaN,37.0,False,False,1.69,False,False,...,False,False,NaN,False,4.3,False,False,98.0,36.0,19.216489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25043,True,63,2,NaN,86.0,False,False,2.24,False,False,...,False,False,NaN,False,7.2,False,False,150.0,65.0,35.425033
25046,True,56,2,NaN,65.0,False,False,2.31,False,False,...,False,False,NaN,False,5.1,False,False,98.0,38.0,22.069132
25049,True,47,2,NaN,46.0,False,False,1.93,False,False,...,False,False,NaN,False,3.2,False,False,108.0,28.0,17.915199
25057,True,61,8,NaN,75.0,False,False,2.29,False,False,...,False,False,NaN,False,6.8,False,False,180.0,68.0,27.331622
25061,False,29,3,NaN,84.0,False,False,3.02,False,False,...,False,False,NaN,False,6.1,False,False,152.0,60.0,33.161435

In [4]:
y

array([-16.91666667, -17.16666667, -17.66666667, ..., -17.08333333,
       -17.08333333, -17.08333333])

In [5]:
X_display, y_display = shap.datasets.nhanesi(display=True)

In [6]:
X_display

,sex_isFemale,age,physical_activity,serum_albumin,alkaline_phosphatase,alkaline_phosphatase_isUnacceptable,alkaline_phosphatase_isTestnotdone,SGOT,SGOT_isUnacceptable,SGOT_isTestnotdone,...,urine_hematest_isLarge,urine_hematest_isBlankbutapplicable,sedimentation_rate,sedimentation_rate_isBlankbutapplicable,uric_acid,uric_acid_isUnacceptable,uric_acid_isTestnotdone,systolic_blood_pressure,pulse_pressure,bmi
20751,False,51,3,NaN,85.0,False,False,NaN,True,False,...,False,False,NaN,False,6.2,False,False,110.0,40.0,25.406803
20753,False,41,2,NaN,68.0,False,False,2.27,False,False,...,False,False,NaN,False,7.7,False,False,136.0,54.0,24.588331
20754,True,31,2,NaN,61.0,False,False,1.86,False,False,...,False,False,NaN,False,4.9,False,False,110.0,24.0,23.756502
20755,False,48,2,NaN,58.0,False,False,NaN,True,False,...,False,False,NaN,False,8.4,False,False,126.0,36.0,28.610011
20756,True,29,3,NaN,37.0,False,False,1.69,False,False,...,False,False,NaN,False,4.3,False,False,98.0,36.0,19.216489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25043,True,63,2,NaN,86.0,False,False,2.24,False,False,...,False,False,NaN,False,7.2,False,False,150.0,65.0,35.425033
25046,True,56,2,NaN,65.0,False,False,2.31,False,False,...,False,False,NaN,False,5.1,False,False,98.0,38.0,22.069132
25049,True,47,2,NaN,46.0,False,False,1.93,False,False,...,False,False,NaN,False,3.2,False,False,108.0,28.0,17.915199
25057,True,61,8,NaN,75.0,False,False,2.29,False,False,...,False,False,NaN,False,6.8,False,False,180.0,68.0,27.331622
25061,False,29,3,NaN,84.0,False,False,3.02,False,False,...,False,False,NaN,False,6.1,False,False,152.0,60.0,33.161435

In [7]:
y_display

array([-16.91666667, -17.16666667, -17.66666667, ..., -17.08333333,
       -17.08333333, -17.08333333])

In [9]:
X_display.describe()

,age,physical_activity,serum_albumin,alkaline_phosphatase,SGOT,BUN,calcium,creatinine,potassium,sodium,...,eosinophils,basophils,band_neutrophils,cholesterol,urine_pH,sedimentation_rate,uric_acid,systolic_blood_pressure,pulse_pressure,bmi
count,14264.000000,14264.000000,10671.000000,6321.000000,6275.000000,2926.000000,6218.000000,2582.000000,2984.000000,2995.000000,...,5818.000000,5818.000000,5818.000000,13832.000000,13572.000000,10182.000000,6606.000000,14264.000000,14260.000000,14264.000000
mean,48.905707,2.957656,4.362309,60.169245,2.428056,14.807724,9.670553,1.008172,4.069135,142.369616,...,2.014610,0.131317,0.252320,220.775087,5.628721,16.125516,5.524342,134.133553,50.639902,25.620677
std,15.574155,0.999980,0.328457,25.892123,1.492351,4.455391,0.478994,0.284194,0.344551,3.113626,...,2.084008,0.393272,1.093025,48.390905,0.773717,11.424670,1.467420,24.383336,18.019190,5.104078
min,25.000000,1.000000,2.700000,4.800000,0.270000,0.800000,0.200000,0.400000,2.700000,121.000000,...,0.000000,0.000000,0.000000,53.000000,5.000000,1.000000,0.700000,80.000000,10.000000,12.418360
25%,35.000000,2.000000,4.200000,45.000000,1.800000,12.000000,9.400000,0.900000,3.800000,141.000000,...,0.000000,0.000000,0.000000,187.000000,5.000000,7.000000,4.500000,118.000000,38.000000,22.057446
50%,48.000000,3.000000,4.400000,57.000000,2.200000,14.000000,9.700000,1.000000,4.100000,143.000000,...,1.000000,0.000000,0.000000,217.000000,5.000000,14.000000,5.400000,130.000000,48.000000,24.925918
75%,65.000000,3.000000,4.600000,70.000000,2.600000,17.000000,10.000000,1.100000,4.300000,144.000000,...,3.000000,0.000000,0.000000,249.000000,6.000000,22.000000,6.500000,148.000000,60.000000,28.243033
max,75.000000,8.000000,5.700000,580.000000,31.000000,49.000000,12.500000,9.000000,5.400000,157.000000,...,17.000000,3.000000,22.000000,793.000000,9.000000,72.000000,12.500000,270.000000,170.000000,72.314050

In [18]:
X.columns[X.isna().any()]

Index(['serum_albumin', 'alkaline_phosphatase', 'SGOT', 'BUN', 'calcium',
       'creatinine', 'potassium', 'sodium', 'total_bilirubin', 'serum_protein',
       'red_blood_cells', 'white_blood_cells', 'hemoglobin', 'hematocrit',
       'segmented_neutrophils', 'lymphocytes', 'monocytes', 'eosinophils',
       'basophils', 'band_neutrophils', 'cholesterol', 'urine_pH',
       'sedimentation_rate', 'uric_acid', 'pulse_pressure'],
      dtype='object')

In [21]:
X.columns[X.dtypes == 'object']

Index([], dtype='object')