In [1]:
import pandas as pd
import numpy as np
from tree import AFTSurvivalTree
from dataset import SupportDataset, SyntheticDataset
from sklearn.model_selection import train_test_split
import time

/home/rizkiduwinanto/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('../data/support2.csv')

In [7]:
data = SupportDataset(df)

In [8]:

d = data.get_data()
d

,age,num.co,scoma,avtisst,race,hday,diabetes,dementia,meanbp,wblc,...,resp,temp,pafi,alb,bili,crea,sod,bun,urine,adlsc
1,62.84998,0,0.0,7.000000,other,1,0,0,97.0,6.000000,...,22.0,36.00000,388.00000,1.799805,0.199982,1.199951,141.0,6.51,2502.0,7.0000
2,60.33899,2,44.0,29.000000,white,3,0,0,43.0,17.097656,...,34.0,34.59375,98.00000,3.500000,1.010000,5.500000,132.0,6.51,2502.0,1.0000
3,52.74698,2,0.0,13.000000,white,4,0,0,70.0,8.500000,...,28.0,37.39844,231.65625,3.500000,2.199707,2.000000,134.0,6.51,2502.0,0.0000
4,42.38498,2,0.0,7.000000,white,1,0,0,75.0,9.099609,...,32.0,35.00000,333.30000,3.500000,1.010000,0.799927,139.0,6.51,2502.0,0.0000
5,79.88495,1,26.0,18.666656,white,3,0,0,59.0,13.500000,...,20.0,37.89844,173.31250,3.500000,1.010000,0.799927,143.0,6.51,2502.0,2.0000
6,93.01599,1,55.0,5.000000,white,1,0,0,110.0,10.398438,...,44.0,38.39844,266.62500,3.500000,1.010000,0.699951,140.0,6.51,2502.0,1.0000
7,62.37097,1,0.0,8.000000,white,1,0,0,78.0,11.699219,...,28.0,37.39844,309.50000,4.799805,0.399963,1.599854,132.0,6.51,2502.0,1.0000
8,86.83899,3,26.0,6.500000,white,1,1,0,72.0,13.599609,...,26.0,37.59375,404.75000,3.500000,1.010000,2.000000,139.0,6.51,2502.0,0.0000
9,85.65594,2,26.0,8.500000,black,1,0,1,97.0,9.699219,...,20.0,36.59375,357.12500,3.500000,0.399963,1.000000,143.0,6.51,2502.0,7.0000
10,42.25897,0,0.0,8.000000,hispanic,1,0,0,84.0,11.298828,...,20.0,38.19531,333.30000,4.699219,0.199982,0.799927,139.0,6.51,2502.0,0.4948

In [4]:

X_train, X_test, y_train, y_test = data.get_train_test()

In [5]:
X_train.to_numpy()

array([[93.01599, 1, 55.0, 5.0, 'white', 1, 0, 0, 110.0, 10.3984375,
        101.0, 44.0, 38.39844, 266.625, 3.5, 1.01, 0.69995117, 140.0,
        6.51, 2502.0, 1.0],
       [62.84998, 0, 0.0, 7.0, 'other', 1, 0, 0, 97.0, 6.0, 69.0, 22.0,
        36.0, 388.0, 1.7998047, 0.19998169, 1.19995117, 141.0, 6.51,
        2502.0, 7.0],
       [86.83899, 3, 26.0, 6.5, 'white', 1, 1, 0, 72.0, 13.5996094,
        100.0, 26.0, 37.59375, 404.75, 3.5, 1.01, 2.0, 139.0, 6.51,
        2502.0, 0.0],
       [52.74698, 2, 0.0, 13.0, 'white', 4, 0, 0, 70.0, 8.5, 88.0, 28.0,
        37.39844, 231.65625, 3.5, 2.19970703, 2.0, 134.0, 6.51, 2502.0,
        0.0],
       [42.25897, 0, 0.0, 8.0, 'hispanic', 1, 0, 0, 84.0, 11.2988281,
        94.0, 20.0, 38.19531, 333.3, 4.6992188, 0.19998169, 0.79992676,
        139.0, 6.51, 2502.0, 0.4947999],
       [79.88495, 1, 26.0, 18.666656, 'white', 3, 0, 0, 59.0, 13.5,
        112.0, 20.0, 37.89844, 173.3125, 3.5, 1.01, 0.79992676, 143.0,
        6.51, 2502.0, 2.0],
       [42.38498, 2, 0.0, 7.0, 'white', 1, 0, 0, 75.0, 9.09960938, 88.0,
        32.0, 35.0, 333.3, 3.5, 1.01, 0.79992676, 139.0, 6.51, 2502.0,
        0.0],
       [62.37097, 1, 0.0, 8.0, 'white', 1, 0, 0, 78.0, 11.6992188, 120.0,
        28.0, 37.39844, 309.5, 4.7998047, 0.39996338, 1.59985352, 132.0,
        6.51, 2502.0, 1.0]], dtype=object)